# Generated by Django 5.0.13 on 2025-04-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelmanager',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=8),
        ),
    ]
