# Generated by Django 5.0.14 on 2025-05-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelManager', '0002_hotelmanager_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelmanager',
            name='verificationFile',
            field=models.FileField(blank=True, null=True, upload_to='hotel-manager/verificationFiles/'),
        ),
    ]
