version: "3.8"

services:
  postgres:
    image: postgres:15.1
    ports:
      - "7887:5432"
    env_file: .env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  web:
    build: .
    env_file: .env
    command: >
      sh -c "sleep 5 &&
            python manage.py migrate --noinput &&
            python manage.py shell -c \"from django.contrib.auth import get_user_model; User = get_user_model(); e = '$DJANGO_SUPERUSER_EMAIL'; p = '$DJANGO_SUPERUSER_PASSWORD'; n = 'Admin'; User.objects.filter(email=e).exists() or User.objects.create_superuser(email=e, password=p, name=n)\" &&
            python manage.py collectstatic --noinput &&
            gunicorn -b 0.0.0.0:8000 bookit.wsgi"
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    networks:
      - app-network
    volumes:
      - .:/app

networks:
  app-network:
