version: "3.8"

services:
  postgres:
    image: postgres:15.1
    ports:
      - "7887:5432"
    env_file: .env
    volumes:
      - $HOME/docker/volumes/Bookit/postgres:/var/lib/postgresql/data
    networks:
      - app-network

  web:
    build: .
    env_file: .env
    command: >
      sh -c "python manage.py makemigrations --noinput &&
             python manage.py migrate --noinput &&
             python manage.py collectstatic --noinput &&
             gunicorn -b 0.0.0.0:8000 bookit.wsgi"
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    networks:
      - app-network

networks:
  app-network:
