services:
  - type: web
    name: bookit-backend
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bookit-db
          property: connectionString
      - key: SERVER_URL
        value: https://bookit.onrender.com

  - type: postgres
    name: bookit-db
    plan: free
