# Generated by Django 5.0.14 on 2025-06-05 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_number',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
