# Generated by Django 5.0.14 on 2025-05-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_emailverificationcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationcode',
            name='code',
            field=models.CharField(max_length=4),
        ),
        migrations.DeleteModel(
            name='HotelManager',
        ),
    ]
