# Generated by Django 5.0.14 on 2025-05-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_emailverificationcode_code_delete_hotelmanager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='created_at',
            new_name='create_datetime',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='adminID',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customerID',
        ),
        migrations.AddField(
            model_name='user',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='modify_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
