# Generated by Django 5.0.14 on 2025-07-15 08:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotelManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_type', models.CharField(choices=[('Wi-Fi', 'Wi-Fi'), ('Parking', 'Parking'), ('Restaurant', 'Restaurant'), ('CoffeShop', 'CoffeShop'), ('Room Service', 'Room Service'), ('Laundry Service', 'Laundry Service'), ('Support Agent', 'Support Agent'), ('Elevator', 'Elevator'), ('Safebox', 'Safebox'), ('TV', 'TV'), ('FreeBreakFast', 'FreeBreakFast'), ('Meeting Room', 'Meeting Room'), ('Child Care', 'Child Care'), ('Pool', 'Pool'), ('Gym', 'Gym'), ('Taxi', 'Taxi'), ('Pets Allowed', 'Pets Allowed'), ('Shopping Mall', 'Shopping Mall')], max_length=65)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('modify_datetime', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('location', models.TextField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='hotel/images/')),
                ('hotel_iban_number', models.CharField(blank=True, max_length=24)),
                ('rate', models.PositiveSmallIntegerField(default=0)),
                ('rate_number', models.IntegerField(default=0)),
                ('hotel_license', models.ImageField(upload_to='hotel/licenses/')),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=8)),
                ('discount', models.DecimalField(decimal_places=2, default=0, help_text='Discount percentage (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('discount_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Expired', 'Expired')], default='Inactive', max_length=10)),
                ('discount_start_date', models.DateTimeField(blank=True, null=True)),
                ('discount_end_date', models.DateTimeField(blank=True, null=True)),
                ('hotel_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelManager.hotelmanager')),
                ('facilities', models.ManyToManyField(blank=True, to='hotel.hotelfacility')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
