# Generated by Django 5.0.14 on 2025-06-05 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_hotel_discount_hotel_discount_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelfacility',
            name='facility_type',
            field=models.CharField(choices=[('Wi-Fi', 'Wi-Fi'), ('Parking', 'Parking'), ('Restaurant', 'Restaurant'), ('CoffeShop', 'CoffeShop'), ('Room Service', 'Room Service'), ('Laundry Service', 'Laundry Service'), ('Support Agent', 'Support Agent'), ('Elevator', 'Elevator'), ('Safebox', 'Safebox'), ('TV', 'TV'), ('FreeBreakFast', 'FreeBreakFast'), ('Meeting Room', 'Meeting Room'), ('Child Care', 'Child Care'), ('Pool', 'Pool'), ('Gym', 'Gym'), ('Taxi', 'Taxi'), ('Pets Allowed', 'Pets Allowed'), ('Shopping Mall', 'Shopping Mall')], max_length=65),
        ),
    ]
