# Generated by Django 5.0.14 on 2025-06-05 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_alter_reservation_id_alter_reservation_room_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='count_of_guests',
        ),
    ]
